; Generated by cobolana-compiler (sBPF backend)
; COBOL Program: 

.section .rodata
msg_HELLO-MSG:
    .byte 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x43, 0x6f, 0x62, 0x6f, 0x6c, 0x61, 0x6e, 0x61
msg_HELLO-MSG_len:
    .word 14

.section .text
.globl entrypoint
entrypoint:
    ; CALL sol_log_(HELLO-MSG, 14)
    lddw %r1, msg_HELLO-MSG
    mov %r2, 14
    call 0x207559bd  ; sol_log_ syscall hash
    mov %r0, 0
    exit
